title = "sec-dev.de - paperless"
baseURL = "https://sec-dev.de"
languageCode = "de-de"
theme = "ananke"
publishdir = "docs/"
#themesDir = "../.."

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Papierloses Büro"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/rsmuc/rsmuc.github.io"
  gitlab = ""
  linkedin = ""
  mastodon = "https://mastodon.bayern/@secdev"
  slack = ""
  stackoverflow = ""
  rss = "https://rsmuc.github.io/index.xml"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #background_color_class = "bg-black"
  featured_image = "documents.jpg"
  recent_posts_number = 5
  disable_share = true
  show_reading_time = true
  mainSections = ["Blog", "Paperless"]
  section = "paperless"
  commentoEnable = false